part of 'keyword.dart';

const _$unitKeywordValues = const [
  UnitKeyword.kArmor,
  UnitKeyword.kArsenal,
  UnitKeyword.kBounty,
  UnitKeyword.kCharge,
  UnitKeyword.kClimbingVehicle,
  UnitKeyword.kCover,
  UnitKeyword.kDeflect,
  UnitKeyword.kDisciplined,
  UnitKeyword.kEnrage,
  UnitKeyword.kEntourage,
  UnitKeyword.kExpertClimber,
  UnitKeyword.kFullPivot,
  UnitKeyword.kGuardian,
  UnitKeyword.kGunslinger,
  UnitKeyword.kHeavyWeaponTeam,
  UnitKeyword.kImmuneBlast,
  UnitKeyword.kImmuneMelee,
  UnitKeyword.kImmunePierce,
  UnitKeyword.kImpervious,
  UnitKeyword.kIndomitable,
  UnitKeyword.kInspire,
  UnitKeyword.kJump,
  UnitKeyword.kLowProfile,
  UnitKeyword.kMasterOfTheForce,
  UnitKeyword.kNimble,
  UnitKeyword.kPlodding,
  UnitKeyword.kPrecise,
  UnitKeyword.kPullingTheStrings,
  UnitKeyword.kReady,
  UnitKeyword.kRelentless,
  UnitKeyword.kReposition,
  UnitKeyword.kScout,
  UnitKeyword.kSentinel,
  UnitKeyword.kSharpshooter,
  UnitKeyword.kSpeeder,
  UnitKeyword.kSpotter,
  UnitKeyword.kStationary,
  UnitKeyword.kSteady,
  UnitKeyword.kTakeCover,
  UnitKeyword.kTeamwork,
  UnitKeyword.kUncannyLuck,
  UnitKeyword.kUnhindered,
  UnitKeyword.kWeakPointRear,
];

const _$weaponKeywordValues = const [
  WeaponKeyword.kArm,
  WeaponKeyword.kBlast,
  WeaponKeyword.kCumbersome,
  WeaponKeyword.kDetonate,
  WeaponKeyword.kFixedFront,
  WeaponKeyword.kFixedRear,
  WeaponKeyword.kHighVelocity,
  WeaponKeyword.kImpact,
  WeaponKeyword.kImmuneDeflect,
  WeaponKeyword.kIon,
  WeaponKeyword.kPierce,
  WeaponKeyword.kSpray,
  WeaponKeyword.kSuppressive,
  WeaponKeyword.kTowCable,
];

const _$upgradeKeywordValues = const [
  UpgradeKeyword.kLeader,
  UpgradeKeyword.kNonCombatant,
  UpgradeKeyword.kRepair,
  UpgradeKeyword.kSidearmMelee,
  UpgradeKeyword.kSidearmRanged,
  UpgradeKeyword.kTreat,
];
